platform :ios, '15.0'

target 'SwipeSpeak' do
  use_frameworks!

  pod 'DZNEmptyDataSet',  '1.8.1'
  pod 'Zephyr',           '~> 3.2'
  pod 'MarkdownView',     '1.3.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
